# Generated by Django 3.2.5 on 2021-07-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата:')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Место')),
            ],
        ),
        migrations.CreateModel(
            name='FilesTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, null=True, verbose_name='Путь к файлу')),
                ('x', models.FloatField(null=True, verbose_name='x')),
                ('y', models.FloatField(null=True, verbose_name='y')),
                ('z', models.FloatField(null=True, verbose_name='z')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.files', verbose_name='Родитель')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.place', verbose_name='Место'),
        ),
    ]
