# Generated by Django 3.2.5 on 2021-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestbl',
            name='file_path',
        ),
        migrations.AddField(
            model_name='files',
            name='file_path',
            field=models.CharField(max_length=500, null=True, verbose_name='Путь к файлу'),
        ),
    ]
