# Generated by Django 3.2.5 on 2021-07-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_auto_20210704_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='comment',
            field=models.CharField(max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
