# Generated by Django 3.2.5 on 2021-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20210706_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestbl',
            name='secondary_x',
            field=models.FloatField(null=True, verbose_name='z'),
        ),
        migrations.AddField(
            model_name='filestbl',
            name='secondary_y',
            field=models.FloatField(null=True, verbose_name='z'),
        ),
        migrations.AddField(
            model_name='filestbl',
            name='secondary_z',
            field=models.FloatField(null=True, verbose_name='z'),
        ),
    ]
