# Generated by Django 3.2.5 on 2021-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20210706_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_path',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default=None, upload_to='data/', verbose_name='Файл'),
        ),
    ]
