# Generated by Django 3.2.5 on 2021-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_auto_20210709_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитан'),
        ),
    ]
