# Generated by Django 3.2.5 on 2021-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_files_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestbl',
            name='secondary_x',
        ),
        migrations.RemoveField(
            model_name='filestbl',
            name='secondary_y',
        ),
        migrations.RemoveField(
            model_name='filestbl',
            name='secondary_z',
        ),
        migrations.AddField(
            model_name='filestbl',
            name='l',
            field=models.FloatField(null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='filestbl',
            name='s',
            field=models.FloatField(null=True, verbose_name='S'),
        ),
    ]
