# Generated by Django 3.2.5 on 2021-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0010_filestbl_old_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, null=True, verbose_name='Имя')),
                ('x', models.FloatField(null=True, verbose_name='x')),
                ('y', models.FloatField(null=True, verbose_name='y')),
                ('z', models.FloatField(null=True, verbose_name='z')),
                ('s', models.FloatField(null=True, verbose_name='S')),
                ('l', models.FloatField(null=True, verbose_name='L')),
                ('x1', models.FloatField(null=True, verbose_name='x2')),
                ('y2', models.FloatField(null=True, verbose_name='y2')),
                ('z3', models.FloatField(null=True, verbose_name='z2')),
                ('s4', models.FloatField(null=True, verbose_name='S2')),
                ('l5', models.FloatField(null=True, verbose_name='L2')),
                ('ox', models.FloatField(null=True, verbose_name='ox')),
                ('oy', models.FloatField(null=True, verbose_name='oy')),
                ('oz', models.FloatField(null=True, verbose_name='oz')),
            ],
        ),
    ]
