# Generated by Django 3.2.5 on 2021-07-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0011_step_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step_2',
            old_name='l5',
            new_name='l2',
        ),
        migrations.RenameField(
            model_name='step_2',
            old_name='s4',
            new_name='s2',
        ),
        migrations.RenameField(
            model_name='step_2',
            old_name='x1',
            new_name='x2',
        ),
        migrations.RenameField(
            model_name='step_2',
            old_name='z3',
            new_name='z2',
        ),
    ]
