# Generated by Django 3.2.5 on 2021-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0013_step_2_ol'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_2',
            name='os',
            field=models.FloatField(null=True, verbose_name='os'),
        ),
    ]
