# Generated by Django 3.2.5 on 2021-07-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0014_step_2_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step_2_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата:')),
                ('file1', models.CharField(default=' ', max_length=300, null=True, verbose_name='Файл1')),
                ('file2', models.CharField(default=' ', max_length=300, null=True, verbose_name='Файл2')),
            ],
        ),
        migrations.AddField(
            model_name='step_2',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energy.step_2_doc', verbose_name='Родитель'),
            preserve_default=False,
        ),
    ]
