# Generated by Django 3.2.5 on 2021-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0015_auto_20210717_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_2',
            name='absolute',
            field=models.FloatField(null=True, verbose_name='absolute'),
        ),
    ]
