# Generated by Django 3.2.5 on 2021-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0016_step_2_absolute'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_2_doc',
            name='comment',
            field=models.CharField(default=' ', max_length=300, null=True, verbose_name='Комментарий'),
        ),
    ]
