# Generated by Django 3.2.5 on 2021-07-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0017_step_2_doc_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files_gps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата:')),
                ('file', models.FileField(default=None, upload_to='data/', verbose_name='Файл')),
                ('comment', models.CharField(default=' ', max_length=500, null=True, verbose_name='Комментарий')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.place', verbose_name='Место')),
            ],
        ),
        migrations.CreateModel(
            name='FilesTbl_gps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True, verbose_name='x')),
                ('y', models.FloatField(null=True, verbose_name='y')),
                ('z', models.FloatField(null=True, verbose_name='z')),
                ('name', models.CharField(max_length=100, verbose_name='Обозначение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.files_gps', verbose_name='Родитель')),
            ],
        ),
    ]
