# Generated by Django 3.2.5 on 2021-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0018_files_gps_filestbl_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_gps',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитан'),
        ),
    ]
