# Generated by Django 3.2.5 on 2021-07-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0019_files_gps_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPS_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата:')),
                ('file1', models.CharField(default=' ', max_length=300, null=True, verbose_name='Файл1')),
                ('file2', models.CharField(default=' ', max_length=300, null=True, verbose_name='Файл2')),
                ('comment', models.CharField(default=' ', max_length=300, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, null=True, verbose_name='Имя')),
                ('x', models.FloatField(null=True, verbose_name='x')),
                ('y', models.FloatField(null=True, verbose_name='y')),
                ('z', models.FloatField(null=True, verbose_name='z')),
                ('x2', models.FloatField(null=True, verbose_name='x2')),
                ('y2', models.FloatField(null=True, verbose_name='y2')),
                ('z2', models.FloatField(null=True, verbose_name='z2')),
                ('ox', models.FloatField(null=True, verbose_name='ox')),
                ('oy', models.FloatField(null=True, verbose_name='oy')),
                ('oz', models.FloatField(null=True, verbose_name='oz')),
                ('ol', models.FloatField(null=True, verbose_name='ol')),
                ('os', models.FloatField(null=True, verbose_name='os')),
                ('absolute', models.FloatField(null=True, verbose_name='absolute')),
                ('v', models.FloatField(null=True, verbose_name='v')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.gps_doc', verbose_name='Родитель')),
            ],
        ),
    ]
