# Generated by Django 3.2.5 on 2021-07-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0020_gps_gps_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='ol',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='os',
        ),
    ]
