# Generated by Django 3.2.5 on 2021-07-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0021_auto_20210729_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='l',
            field=models.FloatField(null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='gps',
            name='l2',
            field=models.FloatField(null=True, verbose_name='L2'),
        ),
        migrations.AddField(
            model_name='gps',
            name='ol',
            field=models.FloatField(null=True, verbose_name='ol'),
        ),
    ]
