# Generated by Django 3.2.5 on 2021-07-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0022_auto_20210730_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='l',
            field=models.FloatField(default=0, null=True, verbose_name='L'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='l2',
            field=models.FloatField(default=0, null=True, verbose_name='L2'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='ol',
            field=models.FloatField(default=0, null=True, verbose_name='ol'),
        ),
    ]
