# Generated by Django 3.2.5 on 2021-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0025_remove_place_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='l',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='l2',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='ol',
        ),
        migrations.AlterField(
            model_name='gps',
            name='absolute',
            field=models.FloatField(default=0, null=True, verbose_name='absolute'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='ox',
            field=models.FloatField(default=0, null=True, verbose_name='ox'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='oy',
            field=models.FloatField(default=0, null=True, verbose_name='oy'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='oz',
            field=models.FloatField(default=0, null=True, verbose_name='oz'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='v',
            field=models.FloatField(default=0, null=True, verbose_name='v'),
        ),
    ]
