# Generated by Django 3.2.5 on 2021-08-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0026_auto_20210812_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps_doc',
            name='file2',
        ),
    ]
