# Generated by Django 3.2.5 on 2021-08-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0027_remove_gps_doc_file2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gps_doc',
            old_name='file1',
            new_name='file',
        ),
        migrations.AddField(
            model_name='gps_doc',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.place', verbose_name='Место'),
        ),
    ]
