# Generated by Django 3.2.5 on 2021-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0028_auto_20210813_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_doc',
            name='file',
            field=models.FileField(default=' ', max_length=300, null=True, upload_to='', verbose_name='Файл'),
        ),
    ]
