# Generated by Django 3.2.5 on 2021-08-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0029_alter_gps_doc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps_doc',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитан'),
        ),
        migrations.AlterField(
            model_name='gps_doc',
            name='file',
            field=models.FileField(default=' ', max_length=300, null=True, upload_to='data/', verbose_name='Файл'),
        ),
    ]
