# Generated by Django 3.2.5 on 2021-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0030_auto_20210813_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps_doc',
            name='date2',
            field=models.DateField(null=True, verbose_name='Дата2:'),
        ),
        migrations.AlterField(
            model_name='gps_doc',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата1:'),
        ),
    ]
