# Generated by Django 3.2.5 on 2021-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0032_auto_20210818_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_2',
            name='newline',
            field=models.BooleanField(default=False, verbose_name='nl'),
        ),
        migrations.AddField(
            model_name='step_2',
            name='newline2',
            field=models.BooleanField(default=False, verbose_name='nl2'),
        ),
    ]
