# Generated by Django 3.2.5 on 2021-08-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0035_remove_gps_doc_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='absolute',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='ox',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='oy',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='oz',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='v',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='y2',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='z2',
        ),
    ]
