# Generated by Django 3.2.5 on 2021-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0038_auto_20210823_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps_doc',
            name='date2',
            field=models.DateField(null=True, verbose_name='Дата2:'),
        ),
    ]
